run_notebooks:
#	cd "1. nanopore insertion analysis/" && python run_notebooks.py
#	cd "2. somatic insertion global analysis" && sh run_notebooks.sh
#	cd "3. genomic feature overlap" && python run_notebooks.py
#	cd "3. genomic feature overlap/gene_overlap" && python run_notebooks.py
	cd "3. genomic feature overlap/damid" && python run_notebooks.py
	cd "4. purity subclonal" && python run_notebooks.py
